apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
    - job_name: 'potato4cut-backend-stage'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['potato-4-cut-stg.danuri-stage.svc.cluster.local:8081']
    - job_name: 'potato4cut-backend-prod'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['potato-4-cut-prod.danuri-prod.svc.cluster.local:8081']
