apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: potato-api-route
  namespace: potato
spec:
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
  hostnames:
    - "potato-api.mya.ong"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: potato-image-backend
          port: 80
