apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mya-ong
  namespace: istio-system
spec:
  secretName: wildcard-mya-ong-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.mya.ong"
    - "mya.ong"
