apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: potato-4cut-route
  namespace: danuri-stage
spec:
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
  hostnames:
    - "stg.potato-4cut-api.mya.ong"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: potato-4-cut
          port: 80
